### ISSUE TITLE
Expose metrics about the exporter received requests

### ISSUE THREAD

**Issue by dgrisonnet** [rhobs/kube-events-exporter#3]
The exporter should expose the following metrics about itself:

- kube_events_exporter_version
- kube_events_exporter_requests_total
- kube_events_exporter_requests_in_flight
- kube_events_exporter_request_duration_seconds_sum
- kube_events_exporter_request_duration_seconds_count
- kube_events_exporter_request_duration_seconds_bucket

**Comment by lilic** [comment]
We should also include error/success metrics when we have actual functionality, maybe a follow issue for that, but this is a good start!

**Comment by dgrisonnet** [comment]
Do you mean something like this?

- kube_events_exporter_scrape_collector_total
- kube_events_exporter_scrape_collector_duration

**Comment by lilic** [comment]
Ideally we would want to have number of errors and 

Maybe something like https://github.com/openshift/cluster-monitoring-operator/blob/6791732eaacae6bc5cbaeb82f0dae05884f94d93/pkg/operator/operator.go#L137-L142 and like we do in kube-state-metrics list/watch error metrics.
